name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (nestjs)
        run: |
          cd nestjs
          npm ci

      - name: Run tests (root)
        run: npm test

      - name: Run tests (nestjs)
        run: |
          cd nestjs
          npm test

      - name: Run tests with coverage (nestjs)
        run: |
          cd nestjs
          npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./nestjs/coverage/lcov.info
          flags: nestjs
          name: nestjs-coverage
        continue-on-error: true

      - name: Build root package
        run: npm run build

      - name: Build nestjs package
        run: |
          cd nestjs
          npm run build

      - name: Check TypeScript compilation
        run: |
          npm run build
          cd nestjs && npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          cd nestjs && npm ci

      - name: Check formatting
        run: |
          # Add prettier check if you use it
          echo "Formatting check passed"
        continue-on-error: true
